// Service, modality and blog article modals. The full text of each card is
// already in the HTML (hidden .card-full block, generated by build.py from
// content/*.yml), so search engines and AI assistants read it without running
// JS. Here that content is only copied into the modal.
// The contact is NOT handled here: build.py writes it straight into
// index.html (.neuro-* slots) from content/common.yml.

function fillModal(prefix, card, iconSelector, titleSelector) {
    const icon = card.querySelector(iconSelector);
    document.getElementById(prefix + 'Icon').innerHTML = icon ? icon.innerHTML : '';
    document.getElementById(prefix + 'Title').textContent =
        card.querySelector(titleSelector).textContent;
    document.getElementById(prefix + 'Body').innerHTML =
        card.querySelector('.card-full').innerHTML;
}

function openServiceModal(key) {
    const card = document.querySelector('.service-card[data-service="' + key + '"]');
    if (!card) return;
    fillModal('modal', card, '.service-icon', 'h3');
    const modal = document.getElementById('serviceModal');
    if (!modal.open) modal.showModal();
}

function closeServiceModal() {
    const modal = document.getElementById('serviceModal');
    if (modal.open) modal.close();
}

function openModalityModal(key) {
    const card = document.querySelector('.modality-item[data-modality="' + key + '"]');
    if (!card) return;
    fillModal('modalityModal', card, '.modality-icon', 'h4');
    const modal = document.getElementById('modalityModal');
    if (!modal.open) modal.showModal();
}

function closeModalityModal() {
    const modal = document.getElementById('modalityModal');
    if (modal.open) modal.close();
}

function openBlogModal(key) {
    const card = document.querySelector('.blog-card[data-blog="' + key + '"]');
    if (!card) return;
    const thumb = card.querySelector('.blog-thumb picture, .blog-thumb img');
    const cover = document.getElementById('blogModalCover');
    cover.innerHTML = '';
    if (thumb) {
        const copy = thumb.cloneNode(true);
        copy.querySelectorAll('img').forEach(function (img) {
            img.removeAttribute('loading');
        });
        cover.appendChild(copy);
    }
    cover.hidden = !thumb;
    document.getElementById('blogModalTitle').textContent =
        card.querySelector('h4').textContent;
    document.getElementById('blogModalBody').innerHTML =
        card.querySelector('.card-full').innerHTML;
    const modal = document.getElementById('blogModal');
    if (!modal.open) modal.showModal();
}

function closeBlogModal() {
    const modal = document.getElementById('blogModal');
    if (modal.open) modal.close();
}

function toggleMenu() {
    const menu = document.getElementById('mobileMenu');
    menu.classList.toggle('active');
    document.body.style.overflow = menu.classList.contains('active') ? 'hidden' : 'auto';
}

document.getElementById('serviceModal').addEventListener('click', function (event) {
    if (event.target === this) closeServiceModal();
});

document.getElementById('modalityModal').addEventListener('click', function (event) {
    if (event.target === this) closeModalityModal();
});

document.getElementById('blogModal').addEventListener('click', function (event) {
    if (event.target === this) closeBlogModal();
});
